// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2Yz5-Yz7xY2I4jiTca-DuoO1zc8zWwcM',
    appId: '1:492955614086:ios:9d7ec89903fbdce91e8a07',
    messagingSenderId: '492955614086',
    projectId: 'doctor-appointment-team-2026',
    storageBucket: 'doctor-appointment-team-2026.firebasestorage.app',
    iosBundleId: 'com.example.appointmentBookingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2Yz5-Yz7xY2I4jiTca-DuoO1zc8zWwcM',
    appId: '1:492955614086:ios:9d7ec89903fbdce91e8a07',
    messagingSenderId: '492955614086',
    projectId: 'doctor-appointment-team-2026',
    storageBucket: 'doctor-appointment-team-2026.firebasestorage.app',
    iosBundleId: 'com.example.appointmentBookingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbVueBj9OBr7G8cjD6erX-W3eeqh9kaRs',
    appId: '1:492955614086:web:0db648f5dbb76a841e8a07',
    messagingSenderId: '492955614086',
    projectId: 'doctor-appointment-team-2026',
    authDomain: 'doctor-appointment-team-2026.firebaseapp.com',
    storageBucket: 'doctor-appointment-team-2026.firebasestorage.app',
    measurementId: 'G-E9G9513PB3',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbVueBj9OBr7G8cjD6erX-W3eeqh9kaRs',
    appId: '1:492955614086:web:0db648f5dbb76a841e8a07',
    messagingSenderId: '492955614086',
    projectId: 'doctor-appointment-team-2026',
    authDomain: 'doctor-appointment-team-2026.firebaseapp.com',
    storageBucket: 'doctor-appointment-team-2026.firebasestorage.app',
    measurementId: 'G-E9G9513PB3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmUlZFRcAnFazfCeua0f-d22H5u8hLXxo',
    appId: '1:492955614086:android:9383ea3d56ae3a921e8a07',
    messagingSenderId: '492955614086',
    projectId: 'doctor-appointment-team-2026',
    storageBucket: 'doctor-appointment-team-2026.firebasestorage.app',
  );
}
