import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:firebase_core/firebase_core.dart';

import 'firebase_options.dart';

import 'package:appointment_booking_app/core/routes/app_router.dart';
import 'package:appointment_booking_app/core/routes/auth_state_listenable.dart';
import 'package:appointment_booking_app/core/theme/app_theme.dart';
import 'package:appointment_booking_app/data/repositories/appointment_repository.dart';
import 'package:appointment_booking_app/data/repositories/auth_repository.dart';
import 'package:appointment_booking_app/data/repositories/doctor_repository.dart';
import 'package:appointment_booking_app/data/repositories/firebase_auth_repository.dart';
import 'package:appointment_booking_app/data/repositories/firestore_appointment_repository.dart';
import 'package:appointment_booking_app/data/repositories/firestore_doctor_repository.dart';
import 'package:appointment_booking_app/data/repositories/mock_notification_repository.dart';
import 'package:appointment_booking_app/data/repositories/notification_repository.dart';
import 'package:appointment_booking_app/presentation/auth/cubit/auth_cubit.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase using the configuration generated by FlutterFire.
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(const AppointmentBookingApp());
}

class AppointmentBookingApp extends StatefulWidget {
  const AppointmentBookingApp({super.key, this.authRepository});

  /// Allows tests to supply the existing mock implementation without
  /// initializing Firebase. Production uses [FirebaseAuthRepository].
  final AuthRepository? authRepository;

  @override
  State<AppointmentBookingApp> createState() => _AppointmentBookingAppState();
}

class _AppointmentBookingAppState extends State<AppointmentBookingApp> {
  late final AuthStateListenable _authState;
  late final AuthRepository _authRepository;
  late final DoctorRepository _doctorRepository;
  late final AppointmentRepository _appointmentRepository;
  late final MockNotificationRepository _notificationRepository;
  late final AuthCubit _authCubit;
  late final AppRouter _appRouter;

  @override
  void initState() {
    super.initState();

    // Keeps the router independent from Firebase implementation.
    _authState = AuthStateListenable();

    // Firebase Authentication repository.
    _authRepository = widget.authRepository ?? FirebaseAuthRepository();

    _authCubit = AuthCubit(
      authRepository: _authRepository,
      authState: _authState,
    );

    // Firestore-backed doctor catalogue and persistent appointment booking.
    _doctorRepository = FirestoreDoctorRepository();
    _appointmentRepository = FirestoreAppointmentRepository();

    // Mock notification repository.
    _notificationRepository = MockNotificationRepository();

    // Application router.
    _appRouter = AppRouter(
      authState: _authState,
    );
  }

  @override
  void dispose() {
    _authCubit.close();
    _authState.dispose();

    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return MultiRepositoryProvider(
      providers: [
        RepositoryProvider<AuthRepository>.value(
          value: _authRepository,
        ),
        RepositoryProvider<DoctorRepository>.value(
          value: _doctorRepository,
        ),
        RepositoryProvider<AppointmentRepository>.value(
          value: _appointmentRepository,
        ),
        RepositoryProvider<NotificationRepository>.value(
          value: _notificationRepository,
        ),
      ],
      child: BlocProvider.value(
        value: _authCubit,
        child: MaterialApp.router(
          title: 'Appointment Booking',
          debugShowCheckedModeBanner: false,
          theme: AppTheme.light,
          routerConfig: _appRouter.router,
        ),
      ),
    );
  }
}
